// <auto-generated />
using Aircraft_Parts_App.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Aircraft_Parts_App.Migrations
{
    [DbContext(typeof(PartContext))]
    [Migration("20260204211959_MakeSupplierIdNullable")]
    partial class MakeSupplierIdNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Aircraft_Parts_App.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Aircraft_Parts_App.Models.Part", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NIIN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("int");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("Parts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Manufacturer = "Boeing",
                            NIIN = "123456789",
                            PartName = "Sonar",
                            QuantityInStock = 12456,
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 2,
                            Manufacturer = "Pratt & Whitney",
                            NIIN = "987654321",
                            PartName = "Turbine Engine",
                            QuantityInStock = 8420,
                            SupplierId = 2
                        },
                        new
                        {
                            Id = 3,
                            Manufacturer = "Lockheed Martin",
                            NIIN = "456789123",
                            PartName = "Landing Gear Assembly",
                            QuantityInStock = 3200,
                            SupplierId = 3
                        },
                        new
                        {
                            Id = 4,
                            Manufacturer = "Northrop Grumman",
                            NIIN = "789123456",
                            PartName = "Avionics Control Unit",
                            QuantityInStock = 15670,
                            SupplierId = 4
                        },
                        new
                        {
                            Id = 5,
                            Manufacturer = "Parker Aerospace",
                            NIIN = "321654987",
                            PartName = "Hydraulic Pump",
                            QuantityInStock = 9850,
                            SupplierId = 4
                        },
                        new
                        {
                            Id = 6,
                            Manufacturer = "Raytheon",
                            NIIN = "654987321",
                            PartName = "Radar System",
                            QuantityInStock = 5430,
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 7,
                            Manufacturer = "General Electric",
                            NIIN = "147258369",
                            PartName = "Fuel Injection Nozzle",
                            QuantityInStock = 22100,
                            SupplierId = 2
                        });
                });

            modelBuilder.Entity("Aircraft_Parts_App.Models.PartCategory", b =>
                {
                    b.Property<int>("PartCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PartCategoryId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("PartId")
                        .HasColumnType("int");

                    b.HasKey("PartCategoryId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PartId");

                    b.ToTable("PartCategories");
                });

            modelBuilder.Entity("Aircraft_Parts_App.Models.PartDetails", b =>
                {
                    b.Property<int>("PartId")
                        .HasColumnType("int");

                    b.Property<string>("Certification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dimensions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplierContact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Weight")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PartId");

                    b.ToTable("PartDetails");

                    b.HasData(
                        new
                        {
                            PartId = 1,
                            Certification = "FAA-PMA",
                            Condition = "New",
                            Dimensions = "120x80x60 cm",
                            Material = "Titanium Alloy",
                            SupplierContact = "boeing.parts@boeing.com",
                            UnitPrice = 12500.00m,
                            Weight = "45.5 kg"
                        },
                        new
                        {
                            PartId = 2,
                            Certification = "FAA-TSO",
                            Condition = "New",
                            Dimensions = "280x150x180 cm",
                            Material = "Nickel-based Superalloy",
                            SupplierContact = "service@pwc.com",
                            UnitPrice = 450000.00m,
                            Weight = "2850 kg"
                        },
                        new
                        {
                            PartId = 3,
                            Certification = "FAA-PMA",
                            Condition = "Overhauled",
                            Dimensions = "200x100x150 cm",
                            Material = "Steel Alloy",
                            SupplierContact = "parts@lockheedmartin.com",
                            UnitPrice = 85000.00m,
                            Weight = "320 kg"
                        },
                        new
                        {
                            PartId = 4,
                            Certification = "DO-160",
                            Condition = "New",
                            Dimensions = "45x35x20 cm",
                            Material = "Aluminum Composite",
                            SupplierContact = "avionics@northropgrumman.com",
                            UnitPrice = 28500.00m,
                            Weight = "12.8 kg"
                        },
                        new
                        {
                            PartId = 5,
                            Certification = "FAA-PMA",
                            Condition = "New",
                            Dimensions = "60x40x35 cm",
                            Material = "Stainless Steel",
                            SupplierContact = "sales@parker.com",
                            UnitPrice = 6750.00m,
                            Weight = "18.5 kg"
                        },
                        new
                        {
                            PartId = 6,
                            Certification = "MIL-STD-461",
                            Condition = "New",
                            Dimensions = "150x80x70 cm",
                            Material = "Composite Materials",
                            SupplierContact = "defense@raytheon.com",
                            UnitPrice = 175000.00m,
                            Weight = "95 kg"
                        },
                        new
                        {
                            PartId = 7,
                            Certification = "FAA-TSO",
                            Condition = "New",
                            Dimensions = "25x15x10 cm",
                            Material = "Ceramic Composite",
                            SupplierContact = "aviation@ge.com",
                            UnitPrice = 3200.00m,
                            Weight = "2.3 kg"
                        });
                });

            modelBuilder.Entity("Aircraft_Parts_App.Models.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SupplierId");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            SupplierId = 1,
                            ContactEmail = "supply@boeing.com",
                            PhoneNumber = "1-800-BOEING-1",
                            SupplierName = "Boeing Supply Chain"
                        },
                        new
                        {
                            SupplierId = 2,
                            ContactEmail = "parts@pw.com",
                            PhoneNumber = "1-800-PW-PARTS",
                            SupplierName = "Pratt & Whitney Distribution"
                        },
                        new
                        {
                            SupplierId = 3,
                            ContactEmail = "orders@lockheed.com",
                            PhoneNumber = "1-800-LM-PARTS",
                            SupplierName = "Lockheed Parts Direct"
                        },
                        new
                        {
                            SupplierId = 4,
                            ContactEmail = "sales@aerocomp.com",
                            PhoneNumber = "1-888-AERO-123",
                            SupplierName = "Aerospace Components Inc"
                        });
                });

            modelBuilder.Entity("Aircraft_Parts_App.Models.Part", b =>
                {
                    b.HasOne("Aircraft_Parts_App.Models.Supplier", "Supplier")
                        .WithMany("Parts")
                        .HasForeignKey("SupplierId");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Aircraft_Parts_App.Models.PartCategory", b =>
                {
                    b.HasOne("Aircraft_Parts_App.Models.Category", "Category")
                        .WithMany("PartCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aircraft_Parts_App.Models.Part", "Part")
                        .WithMany("PartCategories")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Part");
                });

            modelBuilder.Entity("Aircraft_Parts_App.Models.PartDetails", b =>
                {
                    b.HasOne("Aircraft_Parts_App.Models.Part", "Part")
                        .WithOne("PartsDetails")
                        .HasForeignKey("Aircraft_Parts_App.Models.PartDetails", "PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");
                });

            modelBuilder.Entity("Aircraft_Parts_App.Models.Category", b =>
                {
                    b.Navigation("PartCategories");
                });

            modelBuilder.Entity("Aircraft_Parts_App.Models.Part", b =>
                {
                    b.Navigation("PartCategories");

                    b.Navigation("PartsDetails");
                });

            modelBuilder.Entity("Aircraft_Parts_App.Models.Supplier", b =>
                {
                    b.Navigation("Parts");
                });
#pragma warning restore 612, 618
        }
    }
}
