// <auto-generated />
using Fitness_Tracker.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fitness_Tracker.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20260204133415_AddDbContext")]
    partial class AddDbContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fitness_Tracker.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Description = "Non-slip yoga mat for fitness exercises",
                            ImageUrl = "/images/yoga-mat.jpg",
                            Name = "Yoga Mat",
                            Price = 29.99m,
                            Quantity = 50
                        },
                        new
                        {
                            ProductId = 2,
                            Description = "Adjustable dumbbells 5-50 lbs",
                            ImageUrl = "/images/dumbbells.jpg",
                            Name = "Dumbbells Set",
                            Price = 199.99m,
                            Quantity = 25
                        },
                        new
                        {
                            ProductId = 3,
                            Description = "Set of 5 resistance bands with different levels",
                            ImageUrl = "/images/resistance-bands.jpg",
                            Name = "Resistance Bands",
                            Price = 24.99m,
                            Quantity = 100
                        },
                        new
                        {
                            ProductId = 4,
                            Description = "Whey protein powder chocolate flavor 2lb",
                            ImageUrl = "/images/protein.jpg",
                            Name = "Protein Powder",
                            Price = 39.99m,
                            Quantity = 75
                        },
                        new
                        {
                            ProductId = 5,
                            Description = "Insulated stainless steel water bottle 32oz",
                            ImageUrl = "/images/water-bottle.jpg",
                            Name = "Water Bottle",
                            Price = 19.99m,
                            Quantity = 150
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
