// <auto-generated />
using Aircraft_Parts_App.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Aircraft_Parts_App.Migrations
{
    [DbContext(typeof(PartContext))]
    [Migration("20260125000315_initDbMigration")]
    partial class initDbMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Aircraft_Parts_App.Models.AircraftPart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NIIN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Parts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Manufacturer = "Boeing",
                            NIIN = "123456789",
                            PartName = "Sonar",
                            QuantityInStock = 12456
                        },
                        new
                        {
                            Id = 2,
                            Manufacturer = "Pratt & Whitney",
                            NIIN = "987654321",
                            PartName = "Turbine Engine",
                            QuantityInStock = 8420
                        },
                        new
                        {
                            Id = 3,
                            Manufacturer = "Lockheed Martin",
                            NIIN = "456789123",
                            PartName = "Landing Gear Assembly",
                            QuantityInStock = 3200
                        },
                        new
                        {
                            Id = 4,
                            Manufacturer = "Northrop Grumman",
                            NIIN = "789123456",
                            PartName = "Avionics Control Unit",
                            QuantityInStock = 15670
                        },
                        new
                        {
                            Id = 5,
                            Manufacturer = "Parker Aerospace",
                            NIIN = "321654987",
                            PartName = "Hydraulic Pump",
                            QuantityInStock = 9850
                        },
                        new
                        {
                            Id = 6,
                            Manufacturer = "Raytheon",
                            NIIN = "654987321",
                            PartName = "Radar System",
                            QuantityInStock = 5430
                        },
                        new
                        {
                            Id = 7,
                            Manufacturer = "General Electric",
                            NIIN = "147258369",
                            PartName = "Fuel Injection Nozzle",
                            QuantityInStock = 22100
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
