// <auto-generated />
using System;
using Bookstore_App.Models.DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bookstore_App.Migrations
{
    [DbContext(typeof(BookstoreContext))]
    [Migration("20260419233022_AddFKFix")]
    partial class AddFKFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bookstore_App.Models.DomainModels.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "English novelist and essayist.",
                            FirstName = "George",
                            LastName = "Orwell"
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Historian and author.",
                            FirstName = "Yuval",
                            LastName = "Harari"
                        },
                        new
                        {
                            Id = 3,
                            Bio = "Co-author of The Pragmatic Programmer.",
                            FirstName = "Andrew",
                            LastName = "Hunt"
                        });
                });

            modelBuilder.Entity("Bookstore_App.Models.DomainModels.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateOnly>("PublishDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("GenreId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            GenreId = 1,
                            Isbn = "9780451524935",
                            Price = 14.99m,
                            PublishDate = new DateOnly(1949, 6, 8),
                            Title = "1984"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 2,
                            GenreId = 2,
                            Isbn = "9780062316097",
                            Price = 19.99m,
                            PublishDate = new DateOnly(2011, 1, 1),
                            Title = "Sapiens"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 3,
                            GenreId = 3,
                            Isbn = "9780135957059",
                            Price = 44.99m,
                            PublishDate = new DateOnly(2019, 9, 13),
                            Title = "The Pragmatic Programmer"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 1,
                            GenreId = 1,
                            Isbn = "9780385537030",
                            Price = 14.99m,
                            PublishDate = new DateOnly(2011, 9, 13),
                            Title = "The Night Circus"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 2,
                            GenreId = 2,
                            Isbn = "9780593135204",
                            Price = 18.99m,
                            PublishDate = new DateOnly(2021, 5, 4),
                            Title = "Project Hail Mary"
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 3,
                            GenreId = 3,
                            Isbn = "9781250301697",
                            Price = 13.99m,
                            PublishDate = new DateOnly(2019, 5, 1),
                            Title = "The Silent Patient"
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 1,
                            GenreId = 1,
                            Isbn = "9780393592389",
                            Price = 15.99m,
                            PublishDate = new DateOnly(2018, 2, 20),
                            Title = "Educated"
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 2,
                            GenreId = 2,
                            Isbn = "9780316341370",
                            Price = 12.99m,
                            PublishDate = new DateOnly(2018, 4, 10),
                            Title = "Circe"
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 3,
                            GenreId = 3,
                            Isbn = "9780553418026",
                            Price = 11.99m,
                            PublishDate = new DateOnly(2014, 2, 11),
                            Title = "The Martian"
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 1,
                            GenreId = 1,
                            Isbn = "9780071767903",
                            Price = 12.49m,
                            PublishDate = new DateOnly(2011, 8, 30),
                            Title = "The Song of Achilles"
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 2,
                            GenreId = 2,
                            Isbn = "9780735211292",
                            Price = 16.99m,
                            PublishDate = new DateOnly(2018, 10, 16),
                            Title = "Atomic Habits"
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 3,
                            GenreId = 3,
                            Isbn = "9780735219090",
                            Price = 10.99m,
                            PublishDate = new DateOnly(2018, 8, 14),
                            Title = "Where the Crawdads Sing"
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 1,
                            GenreId = 1,
                            Isbn = "9780525559474",
                            Price = 14.49m,
                            PublishDate = new DateOnly(2020, 8, 13),
                            Title = "The Midnight Library"
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 2,
                            GenreId = 2,
                            Isbn = "9780143034902",
                            Price = 13.49m,
                            PublishDate = new DateOnly(2016, 9, 6),
                            Title = "A Gentleman in Moscow"
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 3,
                            GenreId = 3,
                            Isbn = "9780525479988",
                            Price = 15.49m,
                            PublishDate = new DateOnly(2020, 6, 2),
                            Title = "The Vanishing Half"
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 1,
                            GenreId = 1,
                            Isbn = "9780743273565",
                            Price = 10.99m,
                            PublishDate = new DateOnly(1925, 4, 10),
                            Title = "The Great Gatsby"
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 2,
                            GenreId = 2,
                            Isbn = "9780061120084",
                            Price = 7.99m,
                            PublishDate = new DateOnly(1960, 7, 11),
                            Title = "To Kill a Mockingbird"
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 3,
                            GenreId = 3,
                            Isbn = "9781485550464",
                            Price = 9.99m,
                            PublishDate = new DateOnly(1813, 1, 28),
                            Title = "Pride and Prejudice"
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 1,
                            GenreId = 1,
                            Isbn = "9780316769488",
                            Price = 10.99m,
                            PublishDate = new DateOnly(1951, 7, 16),
                            Title = "The Catcher in the Rye"
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 2,
                            GenreId = 2,
                            Isbn = "9780439708180",
                            Price = 10.99m,
                            PublishDate = new DateOnly(1997, 9, 1),
                            Title = "Harry Potter and the Sorcerer's Stone"
                        },
                        new
                        {
                            Id = 21,
                            AuthorId = 3,
                            GenreId = 3,
                            Isbn = "9780547928227",
                            Price = 10.99m,
                            PublishDate = new DateOnly(1937, 9, 21),
                            Title = "The Hobbit"
                        },
                        new
                        {
                            Id = 22,
                            AuthorId = 1,
                            GenreId = 1,
                            Isbn = "9780307474278",
                            Price = 10.99m,
                            PublishDate = new DateOnly(2003, 3, 18),
                            Title = "The Da Vinci Code"
                        },
                        new
                        {
                            Id = 23,
                            AuthorId = 23,
                            GenreId = 8,
                            Isbn = "9780062315007",
                            Price = 10.99m,
                            PublishDate = new DateOnly(1988, 4, 15),
                            Title = "The Alchemist"
                        },
                        new
                        {
                            Id = 24,
                            AuthorId = 24,
                            GenreId = 9,
                            Isbn = "9781933372399",
                            Price = 10.99m,
                            PublishDate = new DateOnly(2008, 4, 17),
                            Title = "The Angel's Game"
                        },
                        new
                        {
                            Id = 25,
                            AuthorId = 25,
                            GenreId = 10,
                            Isbn = "9781944910034",
                            Price = 10.99m,
                            PublishDate = new DateOnly(2001, 4, 17),
                            Title = "The Shadow of the Wind"
                        },
                        new
                        {
                            Id = 26,
                            AuthorId = 26,
                            GenreId = 11,
                            Isbn = "9789603649662",
                            Price = 10.99m,
                            PublishDate = new DateOnly(1987, 9, 4),
                            Title = "Norwegian Wood"
                        },
                        new
                        {
                            Id = 27,
                            AuthorId = 27,
                            GenreId = 12,
                            Isbn = "9780679775430",
                            Price = 10.99m,
                            PublishDate = new DateOnly(1994, 9, 1),
                            Title = "The Wind-Up Bird Chronicle"
                        },
                        new
                        {
                            Id = 28,
                            AuthorId = 28,
                            GenreId = 13,
                            Isbn = "9781400079278",
                            Price = 10.99m,
                            PublishDate = new DateOnly(2002, 9, 12),
                            Title = "Kafka on the Shore"
                        },
                        new
                        {
                            Id = 29,
                            AuthorId = 29,
                            GenreId = 14,
                            Isbn = "9780307706870",
                            Price = 10.99m,
                            PublishDate = new DateOnly(2009, 4, 16),
                            Title = "1Q84"
                        },
                        new
                        {
                            Id = 30,
                            AuthorId = 30,
                            GenreId = 15,
                            Isbn = "9781594483295",
                            Price = 10.99m,
                            PublishDate = new DateOnly(2007, 9, 6),
                            Title = "The Brief Wondrous Life of Oscar Wao"
                        });
                });

            modelBuilder.Entity("Bookstore_App.Models.DomainModels.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Stories driven by imagination.",
                            Name = "Fiction"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Fact-based books.",
                            Name = "Non-Fiction"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Programming and software engineering titles.",
                            Name = "Technology"
                        });
                });

            modelBuilder.Entity("Bookstore_App.Models.DomainModels.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Bookstore_App.Models.DomainModels.Book", b =>
                {
                    b.HasOne("Bookstore_App.Models.DomainModels.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bookstore_App.Models.DomainModels.Genre", "Genre")
                        .WithMany("Books")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Bookstore_App.Models.DomainModels.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Bookstore_App.Models.DomainModels.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bookstore_App.Models.DomainModels.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Bookstore_App.Models.DomainModels.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Bookstore_App.Models.DomainModels.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Bookstore_App.Models.DomainModels.Genre", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
