// <auto-generated />
using FAQ.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FAQ.Migrations
{
    [DbContext(typeof(FaqContext))]
    partial class FaqContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("FAQ.Models.Category", b =>
                {
                    b.Property<string>("CategoryId")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = "general",
                            Name = "General"
                        },
                        new
                        {
                            CategoryId = "hist",
                            Name = "History"
                        });
                });

            modelBuilder.Entity("FAQ.Models.Faq", b =>
                {
                    b.Property<int>("FaqId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TopicId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("FaqId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TopicId");

                    b.ToTable("Faqs");

                    b.HasData(
                        new
                        {
                            FaqId = 1,
                            Answer = "A CSS framework for creating responsive web apps for multiple screen sizes.",
                            CategoryId = "general",
                            Question = "What is Bootstrap?",
                            TopicId = "bootstrap"
                        },
                        new
                        {
                            FaqId = 2,
                            Answer = "A general purpose object oriented language that uses a concise, Java-like syntax.",
                            CategoryId = "general",
                            Question = "What is C#?",
                            TopicId = "csharp"
                        },
                        new
                        {
                            FaqId = 3,
                            Answer = "A general purpose scripting language that executes in a web browser.",
                            CategoryId = "general",
                            Question = "What is JavaScript?",
                            TopicId = "js"
                        },
                        new
                        {
                            FaqId = 4,
                            Answer = "In 2011.",
                            CategoryId = "hist",
                            Question = "When was Bootstrap first released?",
                            TopicId = "bootstrap"
                        },
                        new
                        {
                            FaqId = 5,
                            Answer = "In 2002.",
                            CategoryId = "hist",
                            Question = "When was C# first released?",
                            TopicId = "csharp"
                        },
                        new
                        {
                            FaqId = 6,
                            Answer = "In 1995.",
                            CategoryId = "hist",
                            Question = "When was JavaScript first released?",
                            TopicId = "js"
                        });
                });

            modelBuilder.Entity("FAQ.Models.Topic", b =>
                {
                    b.Property<string>("TopicId")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("TopicId");

                    b.ToTable("Topics");

                    b.HasData(
                        new
                        {
                            TopicId = "bootstrap",
                            Name = "Bootstrap"
                        },
                        new
                        {
                            TopicId = "csharp",
                            Name = "C#"
                        },
                        new
                        {
                            TopicId = "js",
                            Name = "JavaScript"
                        });
                });

            modelBuilder.Entity("FAQ.Models.Faq", b =>
                {
                    b.HasOne("FAQ.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FAQ.Models.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Topic");
                });
#pragma warning restore 612, 618
        }
    }
}
